# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f56fc1b4cf1458481367a1d03c0be67"
name = "test-vanessa-app"
handle = "test-vanessa-app-1"
application_url = "https://leonard-orleans-indie-newcastle.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ntwrk-platform.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_delivery_customizations,read_locations,read_metaobjects,read_products,read_shipping,write_delivery_customizations,write_discounts,write_discounts_allocator_functions,write_locations,write_metaobjects,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://leonard-orleans-indie-newcastle.trycloudflare.com/auth/callback",
  "https://leonard-orleans-indie-newcastle.trycloudflare.com/auth/shopify/callback",
  "https://leonard-orleans-indie-newcastle.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
